### ISSUE TITLE
Gif attractive like to add my own content to the gif can you help me that

### ISSUE THREAD

**Issue by Tharun-tharun** [0xJuancito/0xJuancito#1]
Hey there, I saw your readme profile gif was so attractive, I would like to have the same on my readme profile too can you guide me on how to edit my name and add my own content to it to the gif. Thanks!

**Comment by juancito-dev** [comment]
I followed the instructions in `how to make this gif?` from this repository: https://raw.githubusercontent.com/matyo91/matyo91/main/README.md

**Comment by Tharun-tharun** [comment]
Thanks a lot.

**Comment by Tharun-tharun** [comment]
Hey there again,                                                                                                                                                                                                         I did as mentioned in that given link i edited everything the only thing i can't able to do is i can't make the gif link, So here is the code sandbox link (https://codesandbox.io/s/github-profile-forked-2i350?file=/src/main.js) which i edited, the help which i want from you is can you create a Github gif link for me i don't know how to convert the code into a GitHub gif link.

**Comment by Tharun-tharun** [comment]
> I followed the instructions in `how to make this gif?` from this repository: https://raw.githubusercontent.com/matyo91/matyo91/main/README.md

Hey there again, I did as mentioned in that given link i edited everything the only thing i can't able to do is i can't make the gif link, So here is the code sandbox link (https://codesandbox.io/s/github-profile-forked-2i350?file=/src/main.js) which i edited, the help which i want from you is can you create a Github gif link for me i don't know how to convert the code into a GitHub gif link. I'm sorry to disturb you but this is the only thing I'm struggling with.

**Comment by juancito-dev** [comment]
You'll need to capture your screen into a video first. In MacOS you can do it with Cmd + Shift + 5. On other platforms, you may have to search for some software. I don't have any to recommend on this topic.

After you have the video, you can convert it to a gif with a tool like this: https://ezgif.com/video-to-gif

**Comment by Tharun-tharun** [comment]
Thanks for taking your time to guide me through, means a lot to me, I got it worked, Thanks again!
